### ISSUE TITLE
Linkerd still routes to deleted Kubernetes endpoints

### ISSUE THREAD

**Issue by wjwinner** [linkerd/linkerd#1626]
Issue Type:

- [x ] Bug report
- [ ] Feature request

**What happened**:

I deploy an simple app in k8s, 
```
kubectl get endpoints world-v2-service
world-v2-service   192.168.10.141:7778,192.168.10.144:7778
```
The endpoints ip are '192.168.10.141' and '192.168.10.144';
I can visit by 
```
# curl worldv2.test.com
earth (192.168.10.141)!
```

Then I delete the app and redeploy it, and new endpoints are
```
kubectl get endpoints world-v2-service
world-v2-service   192.168.10.145:7778,192.168.10.146:7778
```

but when I visit the ingress url , the log show
```
E 0907 08:45:51.882 UTC THREAD33: service failure: Failure(Invalid argument: /192.168.10.141:7778 at remote address: /192.168.10.141:7778. Remote Info: Not Available, flags=0x09) with RemoteInfo -> Upstream Address: /192.168.12.192:55967, Upstream Client Id: Not Available, Downstream Address: /192.168.10.141:7778, Downstream Client Id: #/io.l5d.k8s/default/http/world-v2-service, Trace Id: cd10d485ed2ff694.cd10d485ed2ff694<:cd10d485ed2ff694
```
the linkerd is still search for old endpoints.

**Comment by klingerf** [comment]
Hi @wjwinner, thanks for reporting this! I think it's a dupe of #1622, which we just fixed a few days ago. Would you mind trying out the `buoyantio/linkerd:nightly` image to see if it fixes the issue that you're seeing?

**Comment by wjwinner** [comment]
Hi, @klingerf  I have just  tested  1.2.0-32b, 1.2.0 and nightly. The problem still exists。
```
E 0908 02:45:44.001 UTC THREAD28: service failure: Failure(Invalid argument: /192.168.10.149:7778 at remote address: /192.168.10.149:7778. Remote Info: Not Available, flags=0x09) with RemoteInfo -> Upstream Address: /192.168.12.176:50206, Upstream Client Id: Not Available, Downstream Address: /192.168.10.149:7778, Downstream Client Id: #/io.l5d.k8s/default/http/world-v2-service, Trace Id: 083849135a36689c.083849135a36689c<:083849135a36689c
```

**Comment by hawkw** [comment]
Hi @wjwinner,

I've attempted to reproduce this issue in Minikube with the following steps:
+ created a service `world-v1` with `kubectl apply -f linkerd-examples/master/k8s-daemonset/k8s/hello-world-legacy.yml`
```
$ kubectl get endpoints world-v1                                                                                                                                                             
NAME       ENDPOINTS                                         AGE
world-v1   172.17.0.2:7778,172.17.0.3:7778,172.17.0.5:7778   1m
```
+ deleted service `kubectl delete service world-v1`: couldn't reach it as expected
```
http_proxy=$L5D_INGRESS_LB curl -s http://world
invalid response 502
No hosts are available for /svc/world, Dtab.base=[/srv=>/#/io.l5d.k8s/default/http;/host=>/srv;/svc=>/host;/host/world=>/srv/world-v1], Dtab.local=[]. Remote Info: Not Available%    
```
+ re-created service `kubectl apply -f linkerd-examples/master/k8s-daemonset/k8s/hello-world-legacy.yml`
+ `kubectl get endpoints world-v1` gave me different endpoints as expected:
```
kubectl get endpoints world-v1                                                                                                                                                               
NAME       ENDPOINTS                                         AGE
world-v1   172.17.0.2:7778,172.17.0.3:7778,172.17.0.5:7778   6s
```
+ was able to curl service:
```
http_proxy=$L5D_INGRESS_LB curl -s http://world
Hello (172.17.0.22) world (172.17.0.3)!!world (172.17.0.3)!% 
```

As you can see, I wasn't able to reproduce the issue.

What Kubernetes provider are you using? It's possible that I can't recreate this issue in Minikube, but it's occurring due to something specific to whichever provider you're using.

**Comment by weitzj** [comment]
I am using kubernetes 1.7.5 on AWS with flannel. RBAC is enabled. Service has ClusterIP: None
Kubernetes was deployed as multi AZ master, multi AZ node using kops

**Comment by hawkw** [comment]
Okay, thanks for that information @weitzj!

**Comment by wjwinner** [comment]
@hawkw  The endpoints IP had not changed. All two times are "172.17.0.2:7778,172.17.0.3:7778,172.17.0.5:7778"

I use calico, so the endpoints IP change every time when I redeploy my app.

**Comment by hawkw** [comment]
@wjwinner ah, you're right, I must have missed that. I'll see if I can reproduce this with Calico.

**Comment by ihac** [comment]
Same issue here.

```
$ kubectl get endpoints hello
NAME      ENDPOINTS                                                      AGE
hello     192.168.168.233:7777,192.168.172.40:7777,192.168.175.24:7777   4m
$ http_proxy=localhost:4140 curl http://hello
Hello (192.168.172.40) world (192.168.172.42)!!
$
$
$ kubectl delete -f hello-world.yml && kubectl apply -f hello-world.yml
...
$
$ kubectl get endpoints hello
NAME      ENDPOINTS                                                       AGE
hello     192.168.168.235:7777,192.168.168.236:7777,192.168.172.43:7777   9s
$
$ http_proxy=localhost:4140 curl http://hello
Invalid argument: /192.168.172.40:7777 at remote address: /192.168.172.40:7777. Remote Info: Not Available
```

FYI, k8s version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

image tag:
```
$ grep 'image:' linkerd-zipkin-cni.yml
        image: buoyantio/linkerd:nightly
        image: buoyantio/kubectl:v1.4.0
```

pod network: `Calico`

**Comment by hawkw** [comment]
Okay, thanks @weitzj, @wjwinner, and @ihac for the additional information – it looks like this issue only occurs with Calico/Flannel.

**Comment by hawkw** [comment]
Hey folks, can I get you to try the `buoyantio/linkerd:1.2.0-SNAPSHOT` and `buoyantio/namerd:1.2.0-SNAPSHOT` images I just pushed and let me know if the problem persists?

**Comment by wjwinner** [comment]
@hawkw I just tested buoyantio/linkerd:1.2.0-SNAPSHOT. The problem seems to be still there.
```
# kubectl get endpoints
NAME               ENDPOINTS                                 AGE
world-v2-service   192.168.10.151:7778                       4m
```

```
# kubectl logs l5d-g6l8t l5d -n linkerd
E 0912 02:42:29.003 UTC THREAD35: service failure: Failure(Invalid argument: /192.168.10.150:7778 at remote address: /192.168.10.150:7778. Remote Info: Not Available, flags=0x09) with RemoteInfo -> Upstream Address: /192.168.13.97:49542, Upstream Client Id: Not Available, Downstream Address: /192.168.10.150:7778, Downstream Client Id: #/io.l5d.k8s/default/http/world-v2-service, Trace Id: 8f47b4eeec8dd19f.8f47b4eeec8dd19f<:8f47b4eeec8dd19f
```

**Comment by hawkw** [comment]
thanks, that's too bad. we'll keep trying to fix this.

**Comment by ihac** [comment]
@hawkw I tried `linkerd:1.2.0-SNAPSHOT`(not using namerd) but bug still existed.

However, what surprised me most was that, **sometimes**, only 1(or some?) Linkerd instance could not forward request to the rightful endpoint.

```
$ http_proxy=http://node1:4140 curl http://hello
Invalid argument: /192.168.168.236:7777 at remote address: /192.168.168.236:7777. Remote Info: Not Available
$
$ http_proxy=http://node2:4140 curl http://hello
Hello (192.168.175.25) world (192.168.172.46)!!
$
$ http_proxy=http://node3:4140 curl http://hello
Hello (192.168.175.25) world (192.168.168.240)!!
```

It's quite random so I could not reproduce it.

**Comment by hawkw** [comment]
Hi @wjwinner, @weitzj, and @ihac, just wanted to let you all know I have a pull request #1638 that fixes this issue. We'll try to get a hotfix out for this ASAP.

**Comment by ihac** [comment]
Nice! glad to hear it.

**Comment by wjwinner** [comment]
It's working perfect.thanks all

**Comment by hawkw** [comment]
Excellent – we had confirmed that internally, but it's nice to hear. We'll get an official release out soon!

**Comment by Taik** [comment]
@hawkw testing the above tag out (`buoyantio/linkerd:1.2.0.fix4-SNAPSHOT`) and we're seeing a few of these warnings; not sure if its benign:
```
l5d-xcw7g l5d W 0914 13:21:49.739 UTC THREAD35 TraceId:5062f359f2920fbc: k8s ns prod service conversation-srv endpoints watch error Status(Some(Status),Some(v1),Some(ObjectMeta(None,None,None,None,None,None,None,None,None,None,None)),Some(Failure),Some(too old resource version: 77004884 (77815101)),Some(Gone),None,Some(410))
l5d-9hxgb l5d W 0914 13:21:58.461 UTC THREAD41 TraceId:aa44c3d8f2b20d20: k8s ns prod service guest-srv endpoints watch error Status(Some(Status),Some(v1),Some(ObjectMeta(None,None,None,None,None,None,None,None,None,None,None)),Some(Failure),Some(too old resource version: 77007165 (77815142)),Some(Gone),None,Some(410))
l5d-1kfz8 l5d W 0914 13:22:47.102 UTC THREAD37 TraceId:bbff0e2e41bd128a: k8s ns prod service shift-srv endpoints watch error Status(Some(Status),Some(v1),Some(ObjectMeta(None,None,None,None,None,None,None,None,None,None,None)),Some(Failure),Some(too old resource version: 77008615 (77815359)),Some(Gone),None,Some(410))
...
l5d-xcw7g l5d I 0914 13:23:04.961 UTC THREAD10: Reaping /svc/room-srv
l5d-xcw7g l5d I 0914 13:23:05.037 UTC THREAD10: Reaping %/io.l5d.k8s.localnode/10.76.5.82/#/io.l5d.k8s.ns/http/room-srv
...
l5d-9hxgb l5d W 0914 13:23:19.801 UTC THREAD43 TraceId:e10a9374cc05bd70: k8s ns prod service table-srv endpoints watch error Status(Some(Status),Some(v1),Some(ObjectMeta(None,None,None,None,None,None,None,None,None,None,None)),Some(Failure),Some(too old resource version: 77008313 (77815500)),Some(Gone),None,Some(410))
l5d-9hxgb l5d W 0914 13:23:26.171 UTC THREAD43 TraceId:cf2bf18db35c9133: k8s ns prod service conversation-srv endpoints watch error Status(Some(Status),Some(v1),Some(ObjectMeta(None,None,None,None,None,None,None,None,None,None,None)),Some(Failure),Some(too old resource version: 77004884 (77815528)),Some(Gone),None,Some(410))
l5d-9hxgb l5d W 0914 13:23:49.836 UTC THREAD37 TraceId:79898d79a98e89a5: k8s ns prod service auth-srv endpoints watch error Status(Some(Status),Some(v1),Some(ObjectMeta(None,None,None,None,None,None,None,None,None,None,None)),Some(Failure),Some(too old resource version: 77004053 (77815642)),Some(Gone),None,Some(410))
l5d-xcw7g l5d W 0914 13:23:53.073 UTC THREAD22: k8s ns prod service l5d endpoints watch error Status(Some(Status),Some(v1),Some(ObjectMeta(None,None,None,None,None,None,None,None,None,None,None)),Some(Failure),Some(too old resource version: 77783381 (77815657)),Some(Gone),None,Some(410))
l5d-1kfz8 l5d W 0914 13:23:57.514 UTC THREAD25 TraceId:c0e8e62f015e1ab6: k8s ns prod service user-srv endpoints watch error Status(Some(Status),Some(v1),Some(ObjectMeta(None,None,None,None,None,None,None,None,None,None,None)),Some(Failure),Some(too old resource version: 77008477 (77815675)),Some(Gone),None,Some(410))
```

**Comment by hawkw** [comment]
Hi @Taik, after seeing these warnings, can you still route to the correct endpoints for your services?

**Comment by hawkw** [comment]
Hi @Taik, I just wanted to give you a quick update on this. First of all, we've officially released Linkerd version 1.2.1, so you'll want to upgrade your images from `1.2.0.fix4-SNAPSHOT` to `linkerd:1.2.1`. 

Secondly, regarding the "too old resource version" warnings, we've seen those warnings as well in our tests, and we're continuing to look into it. However, we've determined pretty conclusively that they're not related to this issue, as we're also seeing them on Linkerd 1.1.2 and 1.1.3. We suspect this may be related to a recent Kubernetes change, as we hadn't seen this happening in our test deployments of 1.1.2/1.1.3 previously.

Are you also seeing `ChannelClosedException`s in the logs? If so, that would likely indicate that some requests aren't going through, and I'd recommend you open a new issue. Otherwise, the "watch error" warning is probably benign.

**Comment by weitzj** [comment]
@hawkw  Sorry. This happened to me again on 1.2.1

- The service stayed the same as before
- I have updated the deployment/pod inside the service and ran `kubectl apply -f mypoddeployment.yaml`

See:

- badtrace.txt (https://gist.github.com/weitzj/3a57820cf4ca0a37d38ad43387d87154)
- goodtrace.txt (afer linkerd restart)
 (https://gist.github.com/weitzj/41b0065708c714015a11e0a6e3d93909

**Comment by hawkw** [comment]
Hi @weitzj, by any chance, have you seen "too old resource version" error messages in your logs? If so, it's possible you're experiencing a different issue (#1636), which we've recently fixed. Otherwise, I'll be happy to keep looking into this for you.
