### ISSUE TITLE
linkerd 1.3.3 issue with gRPC

### ISSUE THREAD

**Issue by vadimi** [linkerd/linkerd#1728]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
I updated linkerd from `1.1.2` to `1.3.3` in DCOS 1.9 and started getting the following errors in gRPC clients:

from go client:
```
2017/12/05 17:30:05 rpc error: code = ResourceExhausted desc = grpc: received message larger than max (845559858 vs. 4194304)
```

from .net core client:
```
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Failed to deserialize response message.")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
```

It looks like the message becomes invalid. The errors don't happen all the time, I need to call that endpoint multiple times. The message itself is not that big - around `40KB`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
I tried running linkerd locally, but couldn't reproduce this issue.

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files: linkerd 1.3.3, no namerd
- Platform, version, and config files (Kubernetes, DC/OS, etc): DCOS Enterprise 1.9
- Cloud provider or hardware configuration: AWS

linkerd configuration:
```
---
usage:
  enabled: false
admin:
  port: 9990
  ip: 0.0.0.0
namers:
- kind: io.l5d.marathon
  host: leader.mesos
  port: 443
  uriPrefix: "/marathon"
  prefix: "/io.l5d.marathon"
  tls:
    commonName: master.mesos
    trustCerts:
    - "/mnt/mesos/sandbox/.ssl/ca.crt"
routers:
- protocol: h2
  experimental: true
  identifier:
    kind: io.l5d.header.token
  dtab: "/ph=>/$/io.buoyant.rinet;/srv=>/$/io.buoyant.porthostPfx/ph;/svc=>/srv;/marathonId=>/#/io.l5d.marathon;/svc=>/$/io.buoyant.http.domainToPathPfx/marathonId"
  servers:
  - port: 4140
    ip: 0.0.0.0

```

**Comment by vadimi** [comment]
Just tried `1.3.2` in DCOS and this issue not reproducible. But I can reliably reproduce it in `1.3.3`

**Comment by sawyerzhu** [comment]
We encounter same issue with version 1.3.3

**Comment by wmorgan** [comment]
Thanks @vadimi. Good to know that it's something in 1.3.3.

@sawyerzhu can you provide some more details about your environment please?

@vadimi @sawyerzhu It will be much easier to figure this out if we can reproduce it on our side, so if you have some [more] time to spend on working on a repro case, that would really speed up our ability to track this down.

**Comment by vadimi** [comment]
I tried to reproduce it in my local cluster, but unfortunately no luck. But I can steadily reproduce it two AWS DCOS clusters, one is 1.9, another is 1.10.

Considering the issue started happening between `1.3.2` and `1.3.3`, I tried to find a specific commit. Here is what I've got. I've build two linkerd docker images, one from commit https://github.com/linkerd/linkerd/commit/c6f0d2eaeecca80c60314e6f6cb852a31870877a, another from commit https://github.com/linkerd/linkerd/commit/0bd8a91ed51fecc34b86f110382e2077a7b88600. The issue is happening with the first one, but not the second one. It looks like https://github.com/linkerd/linkerd/commit/c6f0d2eaeecca80c60314e6f6cb852a31870877a contributes to the issue somehow.

**Comment by wmorgan** [comment]
@vadimi that's really helpful. Thank you!

**Comment by vadimi** [comment]
@wmorgan I was able to troubleshoot it a bit further. I added some logs to gRPC client to get http2 framing info:

```
2017/12/13 15:24:23 [FrameHeader HEADERS flags=END_HEADERS|PRIORITY stream=59 len=10]
2017/12/13 15:24:23 [FrameHeader DATA stream=59 len=16384]
2017/12/13 15:24:23 [FrameHeader DATA stream=59 len=16384]
2017/12/13 15:24:23 [FrameHeader DATA stream=59 len=16384]
2017/12/13 15:24:23 [FrameHeader DATA stream=59 len=1761]
2017/12/13 15:24:23 [FrameHeader HEADERS flags=END_STREAM|END_HEADERS|PRIORITY stream=59 len=8]
2017/12/13 15:24:23 [FrameHeader HEADERS flags=END_HEADERS|PRIORITY stream=61 len=10]
2017/12/13 15:24:23 [FrameHeader DATA stream=61 len=16384]
2017/12/13 15:24:23 rpc error: code = ResourceExhausted desc = grpc: received message larger than max (845559858 vs. 4194304)
```

I call the same endpoint with the same parameters several times (unary call). Stream `59` is a successful one. Stream `61` is when the error happens. Basically when it reads http2 data frame it should be length-prefixed (at least this is what gRPC expects), so gRPC reads first several bytes to get the length of the message, but this message from stream `61` doesn't have length header, so gRPC reads a few bytes of the message instead and throws an error.

Are there any logs I can get you from linkerd? I still cannot reproduce the issue locally.

**Comment by wmorgan** [comment]
@vadimi That's a really good clue. Thank you.

**Comment by hawkw** [comment]
Hi @vadimi and @sawyerzhu, I've been investigating some problems potentially linked to the root cause of this issue, and I've made some changes that I think may resolve this. 

Since we don't currently have a way to reproduce this failure to test against, would you be interested in trying a snapshot? I've pushed a docker image tagged as `buoyantio/linkerd:1.3.3-SNAPSHOT-grpc`. If you're able, please try running that image and let us know if the issue persists.

**Comment by sawyerzhu** [comment]
@hawkw Thank you. Can you give me the direct download link for linkerd-1.3.3-SNAPSHOT-grpc? I will try. We do not use docker in test environment.

**Comment by hawkw** [comment]
Ah, sorry about that, @vadimi. Unfortunately, the executable is too large to attach to this comment. I've pushed [a branch](https://github.com/linkerd/linkerd/tree/eliza/bytebuf), which you can check out and build from by running `./sbt linkerd/assembly`. Otherwise, I can try to try and find some other way to get you the binary?

**Comment by sawyerzhu** [comment]
Let me build from that branch first.

**Comment by vadimi** [comment]
thanks @hawkw, I just tried this docker image, but unfortunately it's still failing with the same error.

I made another attempt - modified your code a bit to call `f.content.release()` _after_ `updateWindow(sz)`, built my own image and it worked, no errors since. This is basically what I've got (sorry, I'm not a scala guy, I'm sure there is a better way to do this):

```scala
def apply(f: Http2DataFrame, updateWindow: Int => Future[Unit]): Frame.Data = {
    val sz = f.content.readableBytes + f.padding
    val buf = ByteBufAsBuf(f.content.retain())
    val releaser: () => Future[Unit] = {
      if (sz > 0) () => {
        val res = updateWindow(sz)
        f.content.release()
        res
      }
      else () => {
        f.content.release()
        Future.Unit
      }
    }
    Frame.Data(buf, f.isEndStream, releaser)
}
```

**Comment by hawkw** [comment]
That's fantastic @vadimi! Please feel free to open a PR (off of my branch?) and we can look at getting this merged – we can review your changes there.
