### ISSUE TITLE
linkerd namer_state not available when using k8s daemonset transformer

### ISSUE THREAD

**Issue by flodiebold** [linkerd/linkerd#2029]
Issue Type:
- [X] Bug report

**What happened**:
Similar to #1999, the `namer_state` admin endpoint is not available for namers using the k8s daemonset transformer.

**What you expected to happen**:
The `namer_state` should be available for all namers.

**How to reproduce it (as minimally and precisely as possible)**:
Configure two namers:
```    
namers:
    - kind: io.l5d.k8s
      prefix: /io.l5d.k8s.ds
      transformers:
      - kind: io.l5d.k8s.daemonset
        namespace: default
        port: incoming
        service: l5d
    - kind: io.l5d.k8s
```
`/namer_state/io.l5d.k8s.json` exists, but `/namer_state/io.l5d.k8s.ds.json` does not.

**Anything else we need to know?**:
Adapting `NameTreeTransformer.wrap` to pass through admin endpoints seems to fix the problem. I don't have much experience with the code though, so I don't know if it's enough.

**Environment**:
- linkerd current master (f71d01869d60579dc82ca58b983fe2747d5a8842)

**Comment by adleong** [comment]
Hi @flodiebold!  I believe this was fixed in https://github.com/linkerd/linkerd/pull/2005 which should go out with the next Linkerd release.

**Comment by flodiebold** [comment]
Hi @adleong, I think that fixed the analogous problem for interpreters, but it still exists for namers. I was testing with master.

I think the difference is that namers use `wrap` and not `delegatingWrap`, and only the latter was fixed?
